<?php

namespace Blogger\BlogBundle\Entity;

/**
 * AutorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AutorRepository extends \Doctrine\ORM\EntityRepository
{
	public function getAuthors($limit = null)
    {
        $qb = $this->createQueryBuilder('a')
               ->select('a, count(b.id) as numblogs')
               ->join('a.blogs', 'b')
               ->addGroupBy('a.id')
               ->addOrderBy('numblogs', 'DESC');

        if (false === is_null($limit))
            $qb->setMaxResults($limit);
        return $qb->getQuery()
                  ->getResult();

       /*$em = $this->getEntityManager();
		$query = $em->createQuery(
			'SELECT a.nom, a.cognom, b.id, count(b.id) as numblogs
             FROM Blogger\BlogBundle\Entity\Autor a
             INNER JOIN Blogger\BlogBundle\Entity\Blog b
             WITH  a = b.author
             ORDER BY a.data_alta ');
        $autors = $query->getResult();
        return $autors;  */

    }
}
