<?php
namespace Blogger\BlogBundle\Entity;
use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository
{
	public function getTagsCol()
	{
		$em = $this->getEntityManager();
		$query = $em->createQuery(
			'SELECT t.tagname name, count(t.id) num 
             FROM Blogger\BlogBundle\Entity\Tag t 
             JOIN t.blogs b GROUP BY t.id ');
        $blogtags = $query->getResult();
        $tagWeights = array();
       	foreach ($blogtags as $tag) {
       		$tagWeights[$tag['name']] = $tag['num'];
       	}
   	    uksort($tagWeights, function() {
	          return rand() > rand();
	      });
	     $max = max($tagWeights);
	      // un peso máximo de 5
	     $multiplier = ($max > 5) ? 5 / $max : 1;
	     foreach ($tagWeights as &$tag)
	     {
	         $tag = ceil($tag * $multiplier);
	     }
	     return $tagWeights;
	  }              
}
